replicaCount: 1

image:
  repository: git-ci-cd.smartalmaty.kz:8443/opendata/sit-center-landing-nextjs
  pullPolicy: IfNotPresent
  tag: "latest"

env:
  open:
    - name: "test"
      value: "test"

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: smartalmaty.kz
      paths:
        - path: /
          pathType: ImplementationSpecific

  # tls:
  #  - secretName: letsencrypt-smartalmaty
  #    hosts:
  #      - smartalmaty.kz
  tls:
   - secretName: smartalmaty-wildcard-0
     hosts:
       - smartalmaty.kz


resources:
  requests:
    cpu: 0.2
    memory: 256Mi
  limits:
    cpu: 1
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []
affinity: {}

pvc:
  enabled: false
  pvcname: media
  pvcpatch: /media

